server:
  port: 8080

spring:
  application:
    name: infinity-backend
  
  profiles:
    active: dev
  
  # Database configuration
  datasource:
    url: jdbc:h2:mem:infinitydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Security configuration (disabled for development)
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    com.infinity: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 