server:
  port: 8080

spring:
  application:
    name: infinity-backend
  
  # Database configuration for Docker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/infinitydb}
    username: ${SPRING_DATASOURCE_USERNAME:infinity_user}
    password: ${SPRING_DATASOURCE_PASSWORD:infinity_password}
    driver-class-name: org.postgresql.Driver
  
  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  
  # Redis configuration
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000ms

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    com.infinity: INFO
    org.springframework.security: WARN