# Development profile configuration
server:
  port: 8080

spring:
  # DevTools configuration
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  
  # Database configuration for development
  datasource:
    url: jdbc:h2:mem:infinitydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# CORS configuration for development
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://127.0.0.1:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging for development
logging:
  level:
    root: INFO
    com.infinity: DEBUG
    org.springframework.web: DEBUG 