version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/infinitydb
      - SPRING_DATASOURCE_USERNAME=infinity_user
      - SPRING_DATASOURCE_PASSWORD=infinity_password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - infinity-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=infinitydb
      - POSTGRES_USER=infinity_user
      - POSTGRES_PASSWORD=infinity_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - infinity-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - infinity-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - infinity-network

volumes:
  postgres_data:
  redis_data:

networks:
  infinity-network:
    driver: bridge